// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Products Test', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Products Test', async function() {
    await driver.get("https://petlandf.herokuapp.com/")
    await driver.manage().window().setRect({ width: 1049, height: 562 })
    await driver.findElement(By.id("normal_login_pet")).click()
    await driver.findElement(By.id("normal_login_pet")).sendKeys("perro")
    await driver.findElement(By.css(".ant-btn > span")).click()
    await driver.findElement(By.css(".ant-row:nth-child(2) h2")).click()
    await driver.findElement(By.css(".ant-row:nth-child(2) .ant-card-actions svg")).click()
    await driver.executeScript("window.scrollTo(0,409.6000061035156)")
    await driver.findElement(By.css(".ant-row:nth-child(2) > .ant-col .ant-col")).click()
  })
})
